// Copyright (c) 2025-present Viktor Rognas
// Licensed under MIT License

/**
 * Generates platform-specific diff wrapper scripts for external diff tools.
 * Currently supports Beyond Compare with automatic CSV table compare detection.
 */

import * as fs from "fs";
import * as path from "path";
import { ExtensionContext } from "vscode";
import { exists } from "../fs";

/** Common Beyond Compare installation paths on Windows */
const BC_WINDOWS_PATHS = [
  "C:\\Program Files\\Beyond Compare 5\\BCompare.exe",
  "C:\\Program Files\\Beyond Compare 4\\BCompare.exe",
  "C:\\Program Files (x86)\\Beyond Compare 5\\BCompare.exe",
  "C:\\Program Files (x86)\\Beyond Compare 4\\BCompare.exe",
  // User-specific install location
  `${process.env.LOCALAPPDATA}\\Programs\\Beyond Compare 5\\BCompare.exe`,
  `${process.env.LOCALAPPDATA}\\Programs\\Beyond Compare 4\\BCompare.exe`
];

/**
 * Detect Beyond Compare installation path
 * @returns Path to BCompare.exe or undefined if not found
 */
export async function detectBeyondCompare(): Promise<string | undefined> {
  if (process.platform !== "win32") {
    // TODO: Add Linux/Mac support
    return undefined;
  }

  for (const bcPath of BC_WINDOWS_PATHS) {
    if (bcPath && (await exists(bcPath))) {
      return bcPath;
    }
  }

  return undefined;
}

/**
 * Generate bcsvn.bat content for Beyond Compare
 * Automatically uses Table Compare view for CSV files
 *
 * @param bcomparePath Absolute path to BCompare.exe
 * @returns Batch script content
 */
export function generateBcsvnBatContent(bcomparePath: string): string {
  // Escape backslashes for batch file
  const escapedPath = bcomparePath.replace(/\\/g, "\\\\");

  return `@echo off
REM Auto-generated by Sven extension for Beyond Compare integration
REM Detects CSV files and opens in Table Compare view

REM Check if title contains .csv
echo %3 | findstr /i "\\.csv" >nul
if %errorlevel%==0 (
    call "${escapedPath}" /fv="Table Compare" %6 %7 /title1=%3 /title2=%5 /leftreadonly
) else (
    call "${escapedPath}" %6 %7 /title1=%3 /title2=%5 /leftreadonly
)

IF %errorlevel%==0 EXIT /B 0
EXIT /B 1
`;
}

/**
 * Get or create the bcsvn.bat script in extension's global storage
 *
 * @param context Extension context for globalStorageUri
 * @param bcomparePath Optional explicit path to BCompare.exe (auto-detects if not provided)
 * @returns Path to generated bcsvn.bat, or undefined if BC not found
 */
export async function getOrCreateBcsvnScript(
  context: ExtensionContext,
  bcomparePath?: string
): Promise<string | undefined> {
  // Detect BC path if not provided
  const bcPath = bcomparePath || (await detectBeyondCompare());
  if (!bcPath) {
    return undefined;
  }

  // Ensure global storage directory exists
  const storageUri = context.globalStorageUri;
  const storagePath = storageUri.fsPath;

  if (!(await exists(storagePath))) {
    await fs.promises.mkdir(storagePath, { recursive: true });
  }

  // Generate script path
  const scriptPath = path.join(storagePath, "bcsvn.bat");

  // Check if script exists and has correct BC path embedded
  if (await exists(scriptPath)) {
    const existingContent = await fs.promises.readFile(scriptPath, "utf-8");
    if (existingContent.includes(bcPath.replace(/\\/g, "\\\\"))) {
      // Script exists with correct path
      return scriptPath;
    }
  }

  // Generate and write script
  const content = generateBcsvnBatContent(bcPath);
  await fs.promises.writeFile(scriptPath, content, "utf-8");

  return scriptPath;
}

/**
 * Check if a diff tool value indicates Beyond Compare integration
 */
export function isBeyondCompareValue(value: string): boolean {
  const lower = value.toLowerCase();
  return (
    lower === "beyondcompare" ||
    lower === "beyond compare" ||
    lower === "bc" ||
    lower === "bcompare"
  );
}
